name = "market-state-cube-explorer"
main = "worker.js"
compatibility_date = "2026-09-12"
workers_dev = false
preview_urls = false

[vars]
EXPLORER_URL = "http://37.27.112.167:8487"

[[routes]]
pattern = "cube.vaquum.fi"
custom_domain = true
